const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1000,height:800}});await page.setContent(`<html data-hermes-theme="t3-code-theme"><head><style>*{box-sizing:border-box} :root{--dt-card:#202023;--dt-primary:#93b4f4;--dt-primary-foreground:#18181b;--dt-border:#303034;--composer-control-size:24px}body{margin:0} [data-slot=composer-surface]{width:min(var(--composer-width),calc(100vw - 32px));margin:auto;border:1px solid;overflow:hidden} [data-slot=composer-fade]{padding:5px 8px} [data-slot=composer-fade]>.grid{display:grid;grid-template-areas:'menu input controls';grid-template-columns:auto 1fr auto;gap:4px;align-items:center} [class*='grid-area:menu']{grid-area:menu} [class*='grid-area:input']{grid-area:input;min-width:0} [class*='grid-area:controls']{grid-area:controls;display:flex;justify-content:flex-end} .native-controls{display:flex;gap:4px;align-items:center}button{height:24px;white-space:nowrap} [data-slot=composer-rich-input]{min-height:26px;white-space:pre-wrap} </style></head><body><div data-slot="composer-root"><div data-slot="composer-surface"><div data-slot="composer-fade"><div class="grid"><div class="[grid-area:menu]"><button aria-label="Add context">+</button></div><div class="[grid-area:input]"><div><div data-slot="composer-rich-input" contenteditable role="textbox"></div></div></div><div class="[grid-area:controls]"><div class="native-controls"><button data-tour="model-pill">GPT-6-Astra</button><button data-testid="reasoning-pill">Med</button><button aria-label="Voice dictation">Mic</button><button type="submit">Send</button></div></div></div></div></div></div></body></html>`);
const source=fs.readFileSync(require('node:path').join(__dirname,'..','desktop','plugin.js'),'utf8');const css=source.match(/const css = `([\s\S]*?)`/)[1]+source.match(/const pickerCss = `([\s\S]*?)`/)[1];await page.addStyleTag({content:css});
await page.locator('[data-tour=model-pill]').evaluate(e=>e.dataset.t3Provider='openai-codex');
// The installed T3 build's "sm" ComposerControl: text-sm, font-medium, secondary label color.
assert.deepEqual(await page.locator('[data-tour=model-pill]').evaluate(e=>{const c=getComputedStyle(e);return [c.fontSize,c.fontWeight,c.color]}),['14px','500','rgb(118, 118, 118)'],'T3 ComposerControl is 14px medium in the secondary label color');
for(const width of [1000,390]){await page.setViewportSize({width,height:800});const m=await page.evaluate(()=>{const b=s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,bottom:r.bottom,right:r.right}};return{surface:b('[data-slot=composer-surface]'),input:b('[role=textbox]'),model:b('[data-tour=model-pill]'),reason:b('[data-testid=reasoning-pill]'),sep:(()=>{const r=document.querySelector('[data-testid=reasoning-pill]'),c=getComputedStyle(r,'::before');return r.getBoundingClientRect().x+parseFloat(c.left)})(),menu:b('[aria-label="Add context"]'),send:b('[type=submit]')}});assert(m.surface.h>=130,'Roomy composer must be >=130px even empty');assert(m.input.h>=70,'Upper text region must reserve multiline height (T3 min-h-17.5)');assert(m.model.y>=m.input.bottom,'Model must be below input');assert(m.reason.x-m.model.right<20,'Reasoning stays next to model on left');assert(Math.abs((m.sep-m.model.right)-(m.reason.x-(m.sep+1)))<0.5,`Separator centered between model and effort: ${m.sep-m.model.right} vs ${m.reason.x-m.sep-1}`);assert(m.menu.x>m.reason.right,'Attachment is on right');assert(m.send.x>=m.menu.right,'Send is right of attachment');assert(m.send.right<=m.surface.right,'Send not clipped');console.log('PASS composer geometry',width,m)}
// CSS must leave the editor and all native controls in place, not clone them.
const originalInput=await page.locator('[role=textbox]').elementHandle();
await page.locator('[role=textbox]').fill('Line one\nLine two\nLine three');
assert.equal(await page.locator('[role=textbox]').innerText(),'Line one\nLine two\nLine three');
assert(await originalInput.evaluate(e=>e===document.querySelector('[role=textbox]')));
await page.evaluate(()=>{const button=document.querySelector('[data-tour=model-pill]');button.addEventListener('click',()=>button.dataset.clicked='yes')});
await page.locator('[data-tour=model-pill]').click();
assert.equal(await page.locator('[data-tour=model-pill]').getAttribute('data-clicked'),'yes');
await page.setViewportSize({width:1000,height:800});
await page.locator('[data-slot=composer-surface]').screenshot({path:require('node:path').join(require('node:os').tmpdir(),'t3-code-theme-composer-fixture.png')});
await page.evaluate(()=>{const input=document.querySelector('[role=textbox]'); input.textContent=Array.from({length:12},(_,i)=>'Multiline '+i).join('\n');const attachment=document.createElement('div');attachment.dataset.testAttachment='';attachment.style.height='48px';document.querySelector('[data-slot=composer-fade]').prepend(attachment)});
const expanded=await page.locator('[data-slot=composer-surface]').boundingBox();
assert(expanded.height>250,'Long input and attachments expand naturally');
await page.evaluate(()=>{document.querySelector('[data-test-attachment]').remove();document.querySelector('[role=textbox]').textContent=''});
console.log('PASS multiline, attachments, native input identity and existing click handlers');
await page.evaluate(()=>document.documentElement.dataset.hermesTheme='nous');assert((await page.locator('[data-slot=composer-surface]').boundingBox()).height<100,'Other themes retain native compact row');console.log('PASS composer theme isolation');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
